name: Playwright Test

on:
  push:
    branches:
      - main

jobs:
  run-playwright-test:
    name: Run Playwright Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # or 'zulu'
          java-version: '21'      # adjust as needed
          cache: 'maven'          # enables dependency caching

      - name: Build with Maven
        run: mvn -B clean test

      - name: print stuff
        run: ls -ls target/  
      
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: target/surefire-reports
      - name: Show reports
        uses: phoenix-actions/test-reporting@v15
        with:
          name: Playwright Test Report
          reports: target/surefire-reports/*.xml

